apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario-frontend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/puppet1507/mario-aks-gitops.git
    targetRevision: main
    path: helm/mario-frontend
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mario-game-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
